development:
  adapter: postgresql
  database: climb_dev
  host: 127.0.0.1
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: climb_test
  host: 127.0.0.1
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: climb
  host: 127.0.0.1
  pool: 5
  timeout: 5000
