# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 064a84e000fff8492fdc965659b2abb94d2c3d108034f0579e6d35881d1363c6fb40dc8bf20c7c719b7380b67597f1c7cf4014e9973966682d22cea57d5dbae8

test:
  secret_key_base: 40c1abbbb5583964097b0050fcd013526559cfa22c57729f71fe967b59eb883b60c49f1fcd95ac253c3af608fc2b84ffb8425f0fe88e4ead2dbb9b2c4370d22a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
